// The `link` field — a STRUCTURED field (share-by-link), used by the gdocs
// exemplar (doc.mjs, session.mjs) and the photo/canvas exemplars. It is the
// framework's first structured field: ONE declared field that owns several
// named STORED sub-cells, each backed by its own flat SQL column, plus
// declared CONFIG that never reaches a row.
//
//   linkShare: link({ tiers: ['view','comment','edit'], tier: 'view', token: 'autogen' })
//
//   - token  — autogenerated opaque share token (per-row stored cell)
//   - tier   — the CURRENT tier this link grants (per-row stored cell)
//   - tiers  — the allowed-tier domain config (declared once, NOT a column)
//
// The structured field is a NAMESPACE of named value sub-cells: each sub-cell
// mints an ORDINARY value-handle bound to its own generated column, so the
// nested handle `Doc.linkShare.token.is(token)` reuses the SAME `.is()` the
// flat fields already use (concentrate, not a second comparison path). The
// generated column name is derived from the declared shape (no magic strings):
// `<field>__<cell>`, e.g. `linkShare__token`. The structured field's OWN `.is()`
// throws — you compare a sub-cell, never the whole struct.

import { text, link, scope, grant, read, everyone } from '../src/index.mjs';
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import workbench, { entity } from '../src/internal.mjs';
import { lowerToSql, fieldHandle, NonCompilableError } from '../src/scope-sql.mjs';

// --- descriptor shape --------------------------------------------------------

test('link() is a structured field: struct kind, type link, declared cells, tiers config', () => {
  const d = link({ tiers: ['view', 'comment', 'edit'], tier: 'view', token: 'autogen' });
  assert.equal(d.kind, 'struct');
  assert.equal(d.type, 'link');
  // the STORED sub-cells are token + tier, each a value sub-descriptor
  assert.deepEqual(Object.keys(d.cells).sort(), ['tier', 'token']);
  assert.equal(d.cells.token.kind, 'value');
  assert.equal(d.cells.tier.kind, 'value');
  // tiers is CONFIG carried on the descriptor, never a stored cell
  assert.deepEqual(d.tiers, ['view', 'comment', 'edit']);
  assert.equal('tiers' in d.cells, false);
});

// --- the nested compilable handle (scope builder path) -----------------------

test('a struct field handle exposes value sub-handles; its OWN .is throws', () => {
  const d = link({ tiers: ['view', 'edit'], tier: 'view', token: 'autogen' });
  const handle = fieldHandle('linkShare', d);
  // comparing the whole struct is non-compilable — you compare a sub-cell
  assert.throws(() => handle.is('x'), NonCompilableError);
  // a sub-cell is an ordinary value handle
  assert.equal(typeof handle.token.is, 'function');
  assert.equal(typeof handle.tier.is, 'function');
});

test('linkShare.token.is(value) lowers to an eq on the generated column linkShare__token', () => {
  const d = link({ tiers: ['view', 'edit'], tier: 'view', token: 'autogen' });
  const handle = fieldHandle('linkShare', d);
  const { sql, params } = lowerToSql(handle.token.is('tok-1'));
  assert.match(sql, /t0\.linkShare__token = :/);
  const [key] = Object.keys(params);
  assert.equal(params[key], 'tok-1');
});

test('linkShare.token.is(undefined) is the deliberate FALSE (fail-closed, never IS NULL)', () => {
  const d = link({ tiers: ['view', 'edit'], tier: 'view', token: 'autogen' });
  const handle = fieldHandle('linkShare', d);
  const { sql } = lowerToSql(handle.token.is(undefined));
  assert.match(sql, /1 = 0/);
  assert.doesNotMatch(sql, /IS NULL/);
});

// --- the nested handle on a compiled entity (runtime query path) -------------

function makeDoc() {
  return entity('Doc', {
    fields: {
      title: text(),
      linkShare: link({ tiers: ['view', 'comment', 'edit'], tier: 'view', token: 'autogen' }),
    },
    grant: () => [scope(() => everyone()).can(() => grant(read))],
  });
}

// The on-disk schema has one flat column per stored sub-cell.
function seedDb() {
  const db = new DatabaseSync(':memory:');
  db.exec(
    'CREATE TABLE Doc (id TEXT PRIMARY KEY, title TEXT, linkShare__token TEXT, linkShare__tier TEXT)',
  );
  return db;
}

test('Doc.linkShare.token reached through the entity Proxy lowers to its column', () => {
  const Doc = makeDoc();
  const { sql } = lowerToSql(Doc.linkShare.token.is('share-xyz'));
  assert.match(sql, /t0\.linkShare__token = :/);
});

test('a struct write flattens to per-cell columns; a row read reconstructs the namespace', () => {
  const Doc = makeDoc();
  workbench({ db: seedDb() });
  const created = Doc.create({ title: 'memo', linkShare: { token: 'share-xyz', tier: 'comment' } });
  // the row reconstructs linkShare as a namespace object, NOT raw __ columns
  assert.equal(created.title, 'memo');
  assert.equal(created.linkShare.token, 'share-xyz');
  assert.equal(created.linkShare.tier, 'comment');
  assert.equal(created.linkShare__token, undefined);

  // and it is findable by the nested token handle — the session.mjs link-redeem path
  const found = Doc.findOne(Doc.linkShare.token.is('share-xyz'));
  assert.equal(found.id, created.id);
  assert.equal(found.linkShare.tier, 'comment');
});
