// The field-type plugin contract (Phase 1, SPEC §5.1 / §5.4, ADR #9).
//
// A field constructor returns an immutable FIELD DESCRIPTOR. The descriptor is
// the seam every later layer attaches to: the mutation pipeline reads its
// persistence strategy and validate; the entity compiler reads its kind, target
// FK, and derived-check role; the access engine reads its `.can` function (or,
// when absent, strong-inherits the row grant per ADR #4).
//
// The four KINDS are named wholes, not a flag enum (ADR #9): `value` (single
// stored value, whole-value diff), `store` (internally-keyed owned collection),
// `crdt` (custom merge with per-element deltas), `ordered` (fractional-index
// keyspace). Phase 1's blog spine uses `value` and `crdt`; `store`/`ordered`
// ship as the registry grows.

// A field descriptor is frozen so no later layer can mutate a declared field.
// `.can(fn)` returns a NEW frozen descriptor carrying the access function — it
// never mutates the original (declarations are immutable).
function makeDescriptor(props) {
  const descriptor = { access: undefined, ...props };
  descriptor.can = (fn) => {
    const { can, ...fields } = descriptor;
    return makeDescriptor({ ...fields, access: fn });
  };
  return Object.freeze(descriptor);
}

// `value` kind — a single stored value with whole-value diff. The default
// mechanism (the bare kind is the sensible default per the naming rule).
export function text(options = {}) {
  return makeDescriptor({ kind: 'value', type: 'text', ...options });
}
// `text.crdt()` — the `crdt` kind instance for collaborative text. One instance
// of the crdt contract, not a privileged special case (ADR #9).
text.crdt = (options = {}) =>
  makeDescriptor({ kind: 'crdt', type: 'text', ...options });

export function boolean(options = {}) {
  return makeDescriptor({ kind: 'value', type: 'boolean', ...options });
}

export function date(options = {}) {
  return makeDescriptor({ kind: 'value', type: 'date', ...options });
}

// `number()` — a value-kind scalar (integer or float), stored as-is (SQLite
// binds JS numbers directly). `derived` (a recompute-from-row function, e.g.
// wordCount from body) rides the descriptor; its write-path materialization is
// owned by the write/materialization seam, not this declaration.
export function number(options = {}) {
  return makeDescriptor({ kind: 'value', type: 'number', ...options });
}

// `hash()` — a one-way salted password digest. Its own KIND (not `value`): a
// plaintext password is digested on write and is NEVER queryable, so the scope
// compiler refuses to compare it (a hash handle's .is throws — fail closed). A
// hydrated row exposes `row.<field>.verify(plaintext)`; the stored cell is the
// salted digest, never the plaintext.
export function hash(options = {}) {
  return makeDescriptor({ kind: 'hash', type: 'hash', ...options });
}

// `ref(Target)` — a typed foreign key. `target` is explicit (no opaque sugar).
// `role` lets the entity compiler derive `is.<role>()` from the FK (the only
// thing the FK derives — no zero-to-one default grant, ADR #7).
export function ref(target, options = {}) {
  return makeDescriptor({ kind: 'value', type: 'ref', target, ...options });
}

// `link({ tiers, tier, token })` — the framework's first STRUCTURED field: one
// declared field owning several named STORED sub-cells plus declared CONFIG.
// It is the `struct` KIND — a namespace of named value sub-cells, each a real
// flat column, so a nested handle (linkShare.token.is(x)) reuses the ordinary
// value-handle `.is()` (the structured field is not a second comparison path;
// it is a namespace over the SAME value handle). The bare kind is `struct`;
// `type: 'link'` is the named instance (type-first, mechanism-second).
//
//   - token  — autogenerated opaque share token (per-row stored cell)
//   - tier   — the CURRENT tier this link grants (per-row stored cell)
//   - tiers  — allowed-tier domain config (declared once, NEVER a column)
//
// `cells` is the persisted half (each a `value`/text sub-descriptor); every
// other option (`tiers`, the `tier`/`token` defaults) is config. The split is
// explicit so the write path serializes only `cells` and the handle exposes a
// value sub-handle only for `cells` — `tiers` is not a queryable handle because
// it is not row data.
// `map(of, { role, default })` — an internally-keyed owned collection (the
// `store` KIND), each member keyed by id and carrying a value of the declared
// per-member descriptor `of` (doc.mjs: `map(ref('User'), { role:['viewer',
// 'editor'], default:{} })` — a set of collaborators, each a User FK carrying a
// role). It is the framework's owned-collection field: membership lives ON the
// owning entity (AGENTS: an owned relation is a field, not a standalone table),
// not a join table.
//
//   - of    — the per-member value descriptor (a ref, a text, …)
//   - role  — the role names a member may hold (feeds the role-derived checks
//             is.viewer()/is.editor() when the grant is compiled; declared CONFIG,
//             never a per-row column)
//   - default — the empty-collection default
//
// Import-surface scope: this constructor delivers the descriptor the entity
// compiler accepts. On a loaded row the field hydrates into a write handle
// exposing `.add(memberId, role)`/`.remove(memberId)`/`.has(memberId)` against
// the `<Entity>_<field>` side-table (entity.mjs makeMapHandle). The `onAdded`
// event handle (present so effect keys can reference it) and the role-derived
// checks (is.viewer()/is.editor(), runtime-only) remain the `store` kind's
// deferred behavior — the handles exist at import, their firing is deferred.
export function map(of, { role, default: fallback } = {}) {
  return makeDescriptor({
    kind: 'store',
    type: 'map',
    of,
    // role names are declared config (the membership's role domain), never a
    // per-row column — frozen so a later layer cannot mutate the declared set.
    roles: Object.freeze([...(role ?? [])]),
    default: fallback,
    onAdded: Object.freeze({ event: 'added', toString() { return 'map:onAdded'; } }),
  });
}

// `log(entry)` — an append-only, internally-keyed owned collection of STRUCTURED
// entries (the `store` KIND, `type: 'log'`). Each entry has named sub-fields
// declared by the `entry` shape (doc.mjs: `log({ sender: ref('User'), body:
// text() })` — a chat log whose entries each carry a User-FK sender and text
// body). Like `map`, membership lives ON the owning entity (AGENTS: an owned
// relation is a field, not a join table), not a separate entries table.
//
//   - entry — the per-entry sub-field descriptor map (each a value/ref/text
//             descriptor); declared shape, frozen so a later layer cannot mutate it.
//
// Import-surface scope: this constructor delivers the descriptor the entity
// compiler accepts. The append mutation, the `:appended:<id>` event handle, and
// any per-entry query are the `store` kind's Phase-2 merge/event behavior (the
// strategy's apply/diff already fail closed with a loud Phase-2 throw).
export function log(entry = {}) {
  return makeDescriptor({
    kind: 'store',
    type: 'log',
    entry: Object.freeze({ ...entry }),
  });
}

// `presence({ cursor, selection })` — the framework's first NON-PERSISTING
// field: per-connection live state (cursors, selections, typing indicators).
// It is its own KIND (`presence`), a namespace of named live sub-cells. Its
// ephemerality is EMERGENT, not a flag (SPEC §7.2): it engages no persistence
// seam — there is no `presence` strategy entry, so it never serializes, and a
// presence handle is not whole-value comparable in scope (the fieldHandle
// non-value gate throws — fail closed). There is no `persisted: false` label;
// the absence of the seam IS the ephemerality.
//
//   - cells — the declared live sub-cells (cursor, selection, …); the shape is
//             config, frozen so a later layer cannot mutate the declared set.
//
// Import-surface scope: this constructor delivers the descriptor the entity
// compiler accepts. The per-connection broadcast and volatile coalescing are
// the presence kind's deferred live behavior.
export function presence(cells = {}) {
  return makeDescriptor({
    kind: 'presence',
    type: 'presence',
    cells: Object.freeze({ ...cells }),
  });
}

// `state({ values, transitions, effects, auto })` — a finite-state-machine
// field (its own KIND `state`). The field's value is one of a CLOSED `values`
// domain, and the only legal moves are those named in the `transitions` graph
// (fail closed: a move not in the graph is rejected — the value is not a
// free-form column the app may set to anything). doc.mjs: a Doc `status` moving
// draft → shared → archived, with an effect on shared→archived and an `auto`
// rule archiving a shared doc after 90 days.
//
//   - values      — the closed value domain (frozen; never a free column)
//   - transitions — the legal-move graph { from: [to, …] } (frozen)
//   - effects      — keyed by a `state.transition(from, to)` handle → an
//                    in-transaction effect ({ with } / { mutate, with })
//   - auto         — a time-driven auto-transition ({ when, after, to }), sugar
//                    over the schedule time-source (ADR #19), deferred behavior
//
// `state.transition(from, to)` is a STATIC method returning a typed, stable,
// stringifiable transition handle used as a COMPUTED OBJECT KEY in `effects`.
// It is NOT a magic string (AGENTS: authorization/identifiers are never magic
// strings): two calls for the same pair stringify to the SAME key, so the effect
// map is keyed by a derived identifier, not a hand-authored string literal.
//
// Import-surface scope: this constructor delivers the descriptor the entity
// compiler accepts. The transition enforcement (reject illegal moves), the
// effect wiring, and the `auto` scheduler are the state kind's deferred behavior.
export function state({ values, transitions, effects, auto } = {}) {
  return makeDescriptor({
    kind: 'state',
    type: 'state',
    values: Object.freeze([...(values ?? [])]),
    transitions: Object.freeze({ ...(transitions ?? {}) }),
    effects: Object.freeze({ ...(effects ?? {}) }),
    auto,
  });
}
// A typed transition handle. It stringifies to a stable identifier encoding the
// from→to pair, so the same pair always yields the same computed-object key in
// an `effects` map — a derived identifier, never a magic string literal.
state.transition = (from, to) =>
  Object.freeze({
    from,
    to,
    toString() {
      return `transition:${from}->${to}`;
    },
  });

export function link({ tiers, tier, token } = {}) {
  return makeDescriptor({
    kind: 'struct',
    type: 'link',
    cells: Object.freeze({ token: text(), tier: text() }),
    // config carried on the descriptor, never stored per row
    tiers: Object.freeze([...(tiers ?? [])]),
    // the materialization intents for the stored cells (write-path defaults):
    // `token: 'autogen'` means the framework mints the opaque token; `tier` is
    // the starting tier this link grants.
    tokenIntent: token,
    tierDefault: tier,
  });
}
