export function text(...args: any[]): any;
export function ref(...args: any[]): any;
export function boolean(...args: any[]): any;
export function number(...args: any[]): any;
export function date(...args: any[]): any;
export function json(...args: any[]): any;
export function state(...args: any[]): any;
export function map(...args: any[]): any;
export function ordered(...args: any[]): any;
export function ephemeral(...args: any[]): any;
export function blob(...args: any[]): any;
export function derived(...args: any[]): any;
export function projected(...args: any[]): any;
export const fieldType: any;
